name: ci

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    uses: tty-pt/ci/.github/workflows/all-in-one.yml@main
    with:
      name: libndc
      deps: "libqmap,libndx,libssl-dev"
      deps_apk: "libqmap,libndx,openssl-dev"
      deps_pacman: "libqmap,libndx,openssl"
      deps_rpm: "libqmap,libndx,openssl-devel"
      deps_brew: "libqmap,libndx,openssl"
      deps_openbsd: "libqmap,libndx,openssl-3.3.2v0"
      publish_to: "deb,apk,pacman,rpm,brew,openbsd"
    secrets:
      HOST: ${{ secrets.OPENBSD_HOST }}
      USER: ${{ secrets.OPENBSD_USER }}
      SSH_KEY: ${{ secrets.OPENBSD_SSH_KEY }}
      GPG_PRIVATE_KEY: ${{ secrets.OPENBSD_GPG_PRIVATE_KEY }}
      GPG_PASSPHRASE: ${{ secrets.OPENBSD_GPG_PASSPHRASE }}
      GPG_KEYID: ${{ secrets.OPENBSD_GPG_KEY_ID }}
      ABUILD_PRIVATE_KEY: ${{ secrets.ABUILD_PRIVATE_KEY }}
      ABUILD_PUBLIC_KEY: ${{ secrets.ABUILD_PUBLIC_KEY }}
      TAP_TOKEN: ${{ secrets.TAP_TOKEN }}
